# Generated by Django 4.2.15 on 2024-08-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boggle", "0006_userlist_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="report",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="report",
            name="work",
            field=models.TextField(),
        ),
    ]
