# Generated by Django 4.2.15 on 2024-08-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boggle", "0008_alter_report_id_alter_report_title_alter_report_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="task_images_2/"),
        ),
    ]
