# Generated by Django 5.1 on 2024-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boggle', '0007_report_latitude_report_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('post_type', models.CharField(choices=[('일반 게시글', '일반 게시글'), ('참여자 모집', '참여자 모집')], default='일반 게시글', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('nickname', models.CharField(max_length=100)),
                ('recruitment_people', models.PositiveIntegerField(blank=True, null=True)),
                ('recruitment_date', models.DateField(blank=True, null=True)),
                ('recruitment_deadline', models.DateField(blank=True, null=True)),
                ('recruitment_area', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
