# Generated by Django 5.0.6 on 2024-08-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boggle", "0008_communitypost"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlist",
            name="fish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userlist",
            name="turtle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userlist",
            name="weeds",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userlist",
            name="whale",
            field=models.BooleanField(default=False),
        ),
    ]
